name: CI 

on:
  push:
    branches:
      - "main"
    paths:
      - "hangman-api/**"
  pull_request:
    branches: [main]
    paths: ["hangman-api/**"]

jobs:
  # audit:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: inspect
  #       run: |
  #         ls -al 
  #         whoami
  #         pwd
  #         node -v
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: build and build-test
        working-directory: ./hangman-api
        run: |
          npm ci 
          npm run build --if-present
          ls ./dist
          npm test